import type { Nikke } from './types';

export const mockNikkes: Nikke[] = [
  {
    id: '1',
    name: 'Rapi',
    burstType: 'III',
    classType: 'Attacker',
    element: 'Fire',
    manufacturer: 'Elysion',
    weaponType: 'AR',
    imageUrl: 'https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/9/9b/Rapi_icon.png',
    rarity: 'SR',
  },
  {
    id: '2',
    name: 'Anis',
    burstType: 'II',
    classType: 'Defender',
    element: 'Iron',
    manufacturer: 'Tetra',
    weaponType: 'RL',
    imageUrl: 'https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/a/a0/Anis_icon.png',
    rarity: 'SR',
  },
  {
    id: '3',
    name: 'Neon',
    burstType: 'I',
    classType: 'Supporter',
    element: 'Fire',
    manufacturer: 'Elysion',
    weaponType: 'SG',
    imageUrl: 'https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/3/3f/Neon_icon.png',
    rarity: 'SR',
  },
  {
    id: '4',
    name: 'Marian',
    burstType: 'III',
    classType: 'Attacker',
    element: 'Electric',
    manufacturer: 'Elysion',
    weaponType: 'MG',
    imageUrl: 'https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/2/2c/Marian_icon.png',
    rarity: 'SR',
  },
  {
    id: '5',
    name: 'Alice',
    burstType: 'III',
    classType: 'Attacker',
    element: 'Fire',
    manufacturer: 'Tetra',
    weaponType: 'SR',
    imageUrl: 'https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/e/e0/Alice_icon.png',
    rarity: 'SSR',
  },
  {
    id: '6',
    name: 'Liter',
    burstType: 'I',
    classType: 'Supporter',
    element: 'Iron',
    manufacturer: 'Missilis',
    weaponType: 'SMG',
    imageUrl: 'https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/a/a2/Liter_icon.png',
    rarity: 'SSR',
  },
  {
    id: '7',
    name: 'Centi',
    burstType: 'II',
    classType: 'Defender',
    element: 'Iron',
    manufacturer: 'Missilis',
    weaponType: 'RL',
    imageUrl: 'https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/f/f6/Centi_icon.png',
    rarity: 'SSR',
  },
  {
    id: '8',
    name: 'Privaty',
    burstType: 'III',
    classType: 'Attacker',
    element: 'Water',
    manufacturer: 'Elysion',
    weaponType: 'AR',
    imageUrl: 'https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/2/23/Privaty_icon.png',
    rarity: 'SSR',
  },
  {
    id: '9',
    name: 'Scarlet',
    burstType: 'III',
    classType: 'Attacker',
    element: 'Electric',
    manufacturer: 'Pilgrim',
    weaponType: 'AR',
    imageUrl: 'https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/4/47/Scarlet_icon.png',
    rarity: 'SSR',
  },
  {
    id: '10',
    name: 'Harran',
    burstType: 'III',
    classType: 'Attacker',
    element: 'Fire',
    manufacturer: 'Pilgrim',
    weaponType: 'SR',
    imageUrl: 'https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/8b/Harran_icon.png',
    rarity: 'SSR',
  }
];
